"""Optionally hide physical pads from RetroArch.

RetroArch's udev joypad driver enumerates devices with ID_INPUT_JOYSTICK=1
(udev_joypad.c:1053). Clearing that property on the adapters padmap manages
leaves only padmap's virtual pads visible, so pad indices become exactly
0..N-1 in the order the user assigned.

This is a convenience, not a requirement -- padmap computes pad indices from
the live enumeration either way (see retroarch.compute_pad_indices). Hiding
just removes the six dead phantom ports a multi-port adapter otherwise
publishes, which keeps RetroArch's input menus honest.

**Failure mode worth understanding**: while these rules are installed and
padmap is *not* running, the hidden adapters are invisible to RetroArch and
you will have no controllers at all. Rules are therefore scoped to explicit
vid/pid pairs rather than "all joysticks", and are removed by deleting the
file and reloading udev.

Note that `EVIOCGRAB` alone is not enough to achieve this. Grabbing stops
event *delivery* to other readers, but the node stays in udev's enumeration,
so RetroArch still counts it as a pad and assigns it a port. Confirmed
against a live run: three grabbed physical pads plus two virtual ones
produced five configured ports.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

from . import safeio
from .devices import Pad

RULES_PATH = Path("/etc/udev/rules.d/99-padmap.rules")
# udev reads /run/udev/rules.d too, and it is tmpfs. That makes it the right
# place to try these rules: no rebuild, and a reboot undoes them. On NixOS
# /etc/udev/rules.d is a symlink into the store and cannot be written at all.
RUNTIME_RULES_PATH = Path("/run/udev/rules.d/99-padmap.rules")


def is_nixos() -> bool:
    return Path("/etc/NIXOS").exists()

_HEADER = """\
# Generated by padmap. Do not edit; regenerate with `padmap hide`.
#
# Clears ID_INPUT_JOYSTICK on the adapters padmap republishes, so RetroArch's
# udev joypad enumeration sees only padmap's virtual pads.
#
# While this file is installed and padmap is NOT running, these controllers
# are invisible to RetroArch. Undo by deleting this file and re-running
#   sudo udevadm control --reload-rules
#   sudo udevadm trigger --subsystem-match=input
"""


def generate_rules(pads: list[Pad]) -> str:
    """udev rules hiding exactly the given pads' parent devices."""
    seen: set[tuple[int, int]] = set()
    lines = [_HEADER]
    for pad in pads:
        if not pad.vid or not pad.pid:
            # Without a vid/pid there is nothing safe to match on; matching by
            # name would be far too broad.
            lines.append(f"# skipped {pad.name!r}: no usable vid/pid")
            continue
        key = (pad.vid, pad.pid)
        if key in seen:
            continue
        seen.add(key)
        lines.append(f"# {pad.name}")
        lines.append(
            f'SUBSYSTEM=="input", ATTRS{{idVendor}}=="{pad.vid:04x}", '
            f'ATTRS{{idProduct}}=="{pad.pid:04x}", ENV{{ID_INPUT_JOYSTICK}}=""'
        )
        # The same pad again, for when it arrives over Bluetooth.
        #
        # ATTRS{idVendor} walks up to a USB parent, and a Bluetooth pad has
        # none -- so the rule above silently covers nothing and the controller
        # stays visible. That is not theoretical: a Switch Pro paired over
        # Bluetooth was enumerated by RetroArch alongside padmap's clone, both
        # claiming 057e:2009, and the game got the wrong one.
        #
        # Bluetooth HID devices hang off uhid, and the directory name carries
        # the bus and ids: /devices/virtual/misc/uhid/0005:057E:2009.0075/...
        # so this stays as narrow as the USB rule. It cannot catch padmap's own
        # pads: those are /devices/virtual/input/, with no uhid anywhere in the
        # path. Uppercase, because that is how the kernel spells it.
        lines.append(
            f'SUBSYSTEM=="input", DEVPATH=="*/uhid/0005:{pad.vid:04X}:'
            f'{pad.pid:04X}.*", ENV{{ID_INPUT_JOYSTICK}}=""'
        )
    return "\n".join(lines) + "\n"


def targets(discovered: list[Pad], assigned: list[Pad] | None = None) -> list[Pad]:
    """Every physical pad that must be hidden from RetroArch.

    All of them, not just the ones holding a player slot right now. Which
    controller is assigned changes every session; which adapters exist is a
    property of the machine. Generating rules from the assignment is how the
    installed file came to cover a Fightstick and a USB pad but not the
    GameCube adapter plugged in later -- RetroArch then enumerated that
    adapter's four ports and they took player slots 2 through 5, which is
    exactly what was reported.

    It is also actively destructive to regenerate from the assignment: with
    only one controller assigned the result would *drop* the rules covering
    every other adapter, un-hiding pads that were correctly hidden before.

    Union rather than `discovered` alone, so a pad that is assigned but for
    some reason missing from the scan still gets a rule.
    """
    result: list[Pad] = []
    seen: set[tuple[int, int]] = set()
    for pad in list(discovered) + list(assigned or []):
        key = (pad.vid, pad.pid)
        if not pad.vid or not pad.pid or key in seen:
            continue
        seen.add(key)
        result.append(pad)
    return result


def unhidden(pads: list[Pad]) -> list[Pad]:
    """Pads padmap republishes that the installed rules do not cover.

    The rules are generated from whatever was plugged in at the time and then
    left alone, so a controller bought or connected afterwards is simply not
    in them. Nothing notices: padmap goes on working, and RetroArch quietly
    sees the physical adapter *as well as* the virtual pad padmap made from
    it. Measured here after a GameCube adapter was added to a file listing
    only a Fightstick and a USB pad -- RetroArch saw four extra controllers.

    Reads the installed file rather than remembering what was written, for
    the usual reason: what is on disk is what udev applies, and a rebuild, a
    reboot or an edit can all put those two out of step.
    """
    for path in (RUNTIME_RULES_PATH, RULES_PATH):
        # safeio rather than a bare read_text: a rules file that is not valid
        # UTF-8 raises UnicodeDecodeError, which is not an OSError, and
        # `ensure-daemon` calls this unconditionally on every start. A corrupt
        # file in /run would have taken down the whole startup path instead of
        # being reported as covering nothing. default=None because "no file
        # here, try the next path" and "a file covering nothing" are different
        # answers -- an installed but empty file must not fall through to a
        # stale /etc copy.
        text = safeio.read_text(path, default=None)
        if text is not None:
            break
    else:
        # No rules installed at all. Not this function's business to complain
        # -- that is a setup step the user may simply not have taken.
        return []

    covered = {
        (int(m.group(1), 16), int(m.group(2), 16))
        for m in re.finditer(
            r'ATTRS\{idVendor\}=="([0-9a-fA-F]{4})",\s*'
            r'ATTRS\{idProduct\}=="([0-9a-fA-F]{4})"', text)
    }
    missing: list[Pad] = []
    seen: set[tuple[int, int]] = set()
    for pad in pads:
        key = (pad.vid, pad.pid)
        if not pad.vid or not pad.pid or key in covered or key in seen:
            continue
        seen.add(key)
        missing.append(pad)
    return missing


def nix_module_snippet(pads: list[Pad]) -> str:
    """The declarative equivalent, for a system where /etc is read-only."""
    seen: list[tuple[int, int]] = []
    for pad in pads:
        if pad.vid and pad.pid and (pad.vid, pad.pid) not in seen:
            seen.append((pad.vid, pad.pid))
    entries = "\n".join(f'      "{vid:04x}:{pid:04x}"' for vid, pid in seen)
    return (
        "  programs.padmap = {\n"
        "    enable = true;\n"
        "    hideDevices = [\n"
        f"{entries}\n"
        "    ];\n"
        "  };"
    )


def have_root() -> bool:
    return os.geteuid() == 0


def _udevadm(*args: str) -> str:
    """Run udevadm, returning "" on success or a message describing failure.

    Located rather than assumed: on NixOS it lives under
    /run/current-system/sw/bin, which is not always on a root shell's PATH.
    """
    binary = shutil.which("udevadm") or "/run/current-system/sw/bin/udevadm"
    if not Path(binary).exists():
        return "udevadm not found; reload the rules yourself"
    try:
        done = subprocess.run([binary, *args], capture_output=True, text=True)
    except OSError as error:
        return f"could not run udevadm: {error}"
    if done.returncode != 0:
        return f"udevadm {' '.join(args)} failed: {done.stderr.strip()}"
    return ""


def install(rules: str) -> tuple[bool, list[str]]:
    """Write the rules and make udev apply them. (changed, messages).

    Into /run/udev/rules.d: it is tmpfs, so a reboot undoes it, and on NixOS
    /etc/udev/rules.d is a store symlink that cannot be written at all.

    Reloading is not optional. udev keeps its rules in memory, so a file
    written without the reload changes nothing until the next boot -- and a
    controller that is still visible after padmap said it had hidden it is
    precisely the kind of silent gap this project keeps tripping over.

    `changed` is False when the file already said exactly this, so running it
    twice is honest about having done nothing.
    """
    messages: list[str] = []
    target = RUNTIME_RULES_PATH
    # safeio, not read_text: this is a file in /run that padmap did not
    # necessarily write, and read_text on bytes that are not UTF-8 raises
    # UnicodeDecodeError -- not an OSError, so the guard here used to miss it
    # and `sudo padmap hide` tracebacked on a corrupt 99-padmap.rules instead
    # of overwriting it, which is the one thing that would have fixed it.
    existing = safeio.read_text(target)
    if existing == rules:
        return False, [f"{target} already up to date"]

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rules)
    except OSError as error:
        return False, [f"could not write {target}: {error}"]
    messages.append(f"wrote {target}")

    for args in (("control", "--reload-rules"),
                 ("trigger", "--subsystem-match=input")):
        problem = _udevadm(*args)
        messages.append(problem or f"udevadm {args[0]} ok")
    return True, messages


def install_hint(rules: str, pads: list[Pad] | None = None) -> str:
    """Instructions rather than action -- installing these needs root."""
    out = [
        "Rules hiding the physical pads from RetroArch's joypad enumeration.",
        "Try them now -- /run/udev/rules.d is tmpfs, so a reboot undoes this:",
        "",
        f"  sudo mkdir -p {RUNTIME_RULES_PATH.parent}",
        f"  sudo tee {RUNTIME_RULES_PATH} > /dev/null <<'EOF'",
        rules.rstrip("\n"),
        "EOF",
        "  sudo udevadm control --reload-rules",
        "  sudo udevadm trigger --subsystem-match=input",
        "",
        f"To undo:  sudo rm {RUNTIME_RULES_PATH} && "
        f"sudo udevadm control --reload-rules && "
        f"sudo udevadm trigger --subsystem-match=input",
        "",
    ]

    if is_nixos():
        out += [
            "This is NixOS: /etc/udev/rules.d is a symlink into the store and",
            "cannot be written. For a permanent install, import padmap's NixOS",
            "module and set:",
            "",
            nix_module_snippet(pads or []),
            "",
        ]
    else:
        out += [
            f"To make them permanent, write the same rules to {RULES_PATH}.",
            "",
        ]

    out += [
        "Caution: while these rules are active and padmap is not running,",
        "these controllers are invisible to RetroArch entirely.",
        "",
    ]
    return "\n".join(out)
