"""Optionally hide physical pads from RetroArch.

RetroArch's udev joypad driver enumerates devices with ID_INPUT_JOYSTICK=1
(udev_joypad.c:1053). Clearing that property on the adapters padmap manages
leaves only padmap's virtual pads visible, so pad indices become exactly
0..N-1 in the order the user assigned.

This is a convenience, not a requirement -- padmap computes pad indices from
the live enumeration either way (see retroarch.compute_pad_indices). Hiding
just removes the six dead phantom ports a multi-port adapter otherwise
publishes, which keeps RetroArch's input menus honest.

**Failure mode worth understanding**: while these rules are installed and
padmap is *not* running, the hidden adapters are invisible to RetroArch and
you will have no controllers at all. Rules are therefore scoped to explicit
vid/pid pairs rather than "all joysticks", and are removed by deleting the
file and reloading udev.

Note that `EVIOCGRAB` alone is not enough to achieve this. Grabbing stops
event *delivery* to other readers, but the node stays in udev's enumeration,
so RetroArch still counts it as a pad and assigns it a port. Confirmed
against a live run: three grabbed physical pads plus two virtual ones
produced five configured ports.
"""

from __future__ import annotations

from pathlib import Path

from .devices import Pad

RULES_PATH = Path("/etc/udev/rules.d/99-padmap.rules")
# udev reads /run/udev/rules.d too, and it is tmpfs. That makes it the right
# place to try these rules: no rebuild, and a reboot undoes them. On NixOS
# /etc/udev/rules.d is a symlink into the store and cannot be written at all.
RUNTIME_RULES_PATH = Path("/run/udev/rules.d/99-padmap.rules")


def is_nixos() -> bool:
    return Path("/etc/NIXOS").exists()

_HEADER = """\
# Generated by padmap. Do not edit; regenerate with `padmap hide`.
#
# Clears ID_INPUT_JOYSTICK on the adapters padmap republishes, so RetroArch's
# udev joypad enumeration sees only padmap's virtual pads.
#
# While this file is installed and padmap is NOT running, these controllers
# are invisible to RetroArch. Undo by deleting this file and re-running
#   sudo udevadm control --reload-rules
#   sudo udevadm trigger --subsystem-match=input
"""


def generate_rules(pads: list[Pad]) -> str:
    """udev rules hiding exactly the given pads' parent devices."""
    seen: set[tuple[int, int]] = set()
    lines = [_HEADER]
    for pad in pads:
        if not pad.vid or not pad.pid:
            # Without a vid/pid there is nothing safe to match on; matching by
            # name would be far too broad.
            lines.append(f"# skipped {pad.name!r}: no usable vid/pid")
            continue
        key = (pad.vid, pad.pid)
        if key in seen:
            continue
        seen.add(key)
        lines.append(f"# {pad.name}")
        lines.append(
            f'SUBSYSTEM=="input", ATTRS{{idVendor}}=="{pad.vid:04x}", '
            f'ATTRS{{idProduct}}=="{pad.pid:04x}", ENV{{ID_INPUT_JOYSTICK}}=""'
        )
    return "\n".join(lines) + "\n"


def nix_module_snippet(pads: list[Pad]) -> str:
    """The declarative equivalent, for a system where /etc is read-only."""
    seen: list[tuple[int, int]] = []
    for pad in pads:
        if pad.vid and pad.pid and (pad.vid, pad.pid) not in seen:
            seen.append((pad.vid, pad.pid))
    entries = "\n".join(f'      "{vid:04x}:{pid:04x}"' for vid, pid in seen)
    return (
        "  programs.padmap = {\n"
        "    enable = true;\n"
        "    hideDevices = [\n"
        f"{entries}\n"
        "    ];\n"
        "  };"
    )


def install_hint(rules: str, pads: list[Pad] | None = None) -> str:
    """Instructions rather than action -- installing these needs root."""
    out = [
        "Rules hiding the physical pads from RetroArch's joypad enumeration.",
        "Try them now -- /run/udev/rules.d is tmpfs, so a reboot undoes this:",
        "",
        f"  sudo mkdir -p {RUNTIME_RULES_PATH.parent}",
        f"  sudo tee {RUNTIME_RULES_PATH} > /dev/null <<'EOF'",
        rules.rstrip("\n"),
        "EOF",
        "  sudo udevadm control --reload-rules",
        "  sudo udevadm trigger --subsystem-match=input",
        "",
        f"To undo:  sudo rm {RUNTIME_RULES_PATH} && "
        f"sudo udevadm control --reload-rules && "
        f"sudo udevadm trigger --subsystem-match=input",
        "",
    ]

    if is_nixos():
        out += [
            "This is NixOS: /etc/udev/rules.d is a symlink into the store and",
            "cannot be written. For a permanent install, import padmap's NixOS",
            "module and set:",
            "",
            nix_module_snippet(pads or []),
            "",
        ]
    else:
        out += [
            f"To make them permanent, write the same rules to {RULES_PATH}.",
            "",
        ]

    out += [
        "Caution: while these rules are active and padmap is not running,",
        "these controllers are invisible to RetroArch entirely.",
        "",
    ]
    return "\n".join(out)
