//! udev rules that hide physical pads, so only danstick's virtual ones are visible.

/// One controller, as much of it as a rule needs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Hideable {
    pub name: String,
    pub vid: u16,
    pub pid: u16,
}

const HEADER: &str = "\
# Generated by danstick. Do not edit; regenerate with `danstick hide`.
#
# Clears ID_INPUT_JOYSTICK on the adapters danstick republishes, so a udev
# joypad enumeration sees only danstick's virtual pads.
#
# While this file is installed and danstick is NOT running, these controllers
# are invisible. Undo by deleting this file and re-running
#   sudo udevadm control --reload-rules
#   sudo udevadm trigger --subsystem-match=input
";

/// udev rules hiding exactly these pads' parent devices.
pub fn generate_rules(pads: &[Hideable]) -> String {
    let mut out = String::from(HEADER);
    let mut seen: Vec<(u16, u16)> = Vec::new();
    for pad in pads {
        if pad.vid == 0 || pad.pid == 0 {
            out.push_str(&format!("# skipped {:?}: no usable vid/pid\n", pad.name));
            continue;
        }
        let key = (pad.vid, pad.pid);
        if seen.contains(&key) {
            continue;
        }
        seen.push(key);
        out.push_str(&format!("# {}\n", pad.name));
        out.push_str(&format!(
            "SUBSYSTEM==\"input\", ATTRS{{idVendor}}==\"{:04x}\", \
             ATTRS{{idProduct}}==\"{:04x}\", ENV{{ID_INPUT_JOYSTICK}}=\"\"\n",
            pad.vid, pad.pid
        ));
        out.push_str(&format!(
            "SUBSYSTEM==\"input\", DEVPATH==\"*/uhid/0005:{:04X}:{:04X}.*\", \
             ENV{{ID_INPUT_JOYSTICK}}=\"\"\n",
            pad.vid, pad.pid
        ));
    }
    out
}

/// All physical pads that must be hidden: union of discovered and assigned.
pub fn targets(discovered: &[Hideable], assigned: &[Hideable]) -> Vec<Hideable> {
    let mut out = Vec::new();
    let mut seen: Vec<(u16, u16)> = Vec::new();
    for pad in discovered.iter().chain(assigned.iter()) {
        let key = (pad.vid, pad.pid);
        if pad.vid == 0 || pad.pid == 0 || seen.contains(&key) {
            continue;
        }
        seen.push(key);
        out.push(pad.clone());
    }
    out
}

/// The vid/pid pairs an installed rules file already covers (parsed from text, not remembered).
pub fn covered(rules: &str) -> Vec<(u16, u16)> {
    let mut out = Vec::new();
    for line in rules.lines() {
        let Some(vendor) = field_after(line, "ATTRS{idVendor}==\"") else {
            continue;
        };
        let Some(product) = field_after(line, "ATTRS{idProduct}==\"") else {
            continue;
        };
        if let (Ok(vid), Ok(pid)) = (
            u16::from_str_radix(&vendor, 16),
            u16::from_str_radix(&product, 16),
        ) {
            if !out.contains(&(vid, pid)) {
                out.push((vid, pid));
            }
        }
    }
    out
}

fn field_after(line: &str, marker: &str) -> Option<String> {
    let rest = line.split_once(marker)?.1;
    let value = rest.split_once('"')?.0;
    (value.len() == 4 && value.chars().all(|c| c.is_ascii_hexdigit())).then(|| value.to_owned())
}

/// Pads danstick republishes that the installed rules do not cover.
pub fn unhidden(pads: &[Hideable], rules: Option<&str>) -> Vec<Hideable> {
    let Some(rules) = rules else {
        return Vec::new();
    };
    let covered = covered(rules);
    let mut out = Vec::new();
    let mut seen: Vec<(u16, u16)> = Vec::new();
    for pad in pads {
        let key = (pad.vid, pad.pid);
        if pad.vid == 0 || pad.pid == 0 || covered.contains(&key) || seen.contains(&key) {
            continue;
        }
        seen.push(key);
        out.push(pad.clone());
    }
    out
}

/// The declarative equivalent, for a system whose /etc is read-only.
pub fn nix_module_snippet(pads: &[Hideable]) -> String {
    let mut seen: Vec<(u16, u16)> = Vec::new();
    for pad in pads {
        let key = (pad.vid, pad.pid);
        if pad.vid != 0 && pad.pid != 0 && !seen.contains(&key) {
            seen.push(key);
        }
    }
    let entries: Vec<String> = seen
        .iter()
        .map(|(vid, pid)| format!("      \"{vid:04x}:{pid:04x}\""))
        .collect();
    format!(
        "  programs.danstick = {{\n    enable = true;\n    hideDevices = [\n{}\n    ];\n  }};",
        entries.join("\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pad(name: &str, vid: u16, pid: u16) -> Hideable {
        Hideable {
            name: name.to_owned(),
            vid,
            pid,
        }
    }

    #[test]
    fn each_pad_gets_a_usb_rule_and_a_bluetooth_rule() {
        let rules = generate_rules(&[pad("Switch Pro", 0x057E, 0x2009)]);
        assert!(rules.contains(r#"ATTRS{idVendor}=="057e""#));
        assert!(rules.contains(r#"ATTRS{idProduct}=="2009""#));
        assert!(rules.contains(r#"DEVPATH=="*/uhid/0005:057E:2009.*""#));
        assert_eq!(
            rules.matches("ID_INPUT_JOYSTICK").count(),
            3,
            "two rules plus the header"
        );
    }

    #[test]
    fn the_bluetooth_rule_is_uppercase_because_the_kernel_spells_it_that_way() {
        let rules = generate_rules(&[pad("Pad", 0x28de, 0x11ff)]);
        assert!(rules.contains("0005:28DE:11FF."), "{rules}");
        assert!(
            rules.contains(r#"=="28de""#),
            "the USB rule stays lowercase"
        );
    }

    #[test]
    fn a_pad_with_no_ids_is_skipped_and_said_so_rather_than_matched_by_name() {
        let rules = generate_rules(&[pad("Nameless", 0, 0)]);
        assert!(rules.contains("no usable vid/pid"));
        assert!(!rules.contains("ATTRS{idVendor}"));
    }

    #[test]
    fn the_same_model_twice_produces_one_pair_of_rules() {
        let pads: Vec<Hideable> = (0..4).map(|_| pad("Mayflash", 0x0079, 0x1843)).collect();
        let rules = generate_rules(&pads);
        assert_eq!(rules.matches("ATTRS{idVendor}").count(), 1);
    }

    #[test]
    fn targets_are_the_union_and_not_just_what_is_assigned() {
        let discovered = [pad("A", 1, 2), pad("B", 3, 4)];
        let assigned = [pad("B", 3, 4), pad("C", 5, 6)];
        let result = targets(&discovered, &assigned);
        assert_eq!(
            result.iter().map(|p| (p.vid, p.pid)).collect::<Vec<_>>(),
            [(1, 2), (3, 4), (5, 6)]
        );
    }

    #[test]
    fn a_pad_with_no_ids_is_never_a_target() {
        assert!(targets(&[pad("X", 0, 0)], &[]).is_empty());
        assert!(targets(&[pad("X", 1, 0)], &[]).is_empty());
    }

    #[test]
    fn what_was_generated_is_read_back_as_covered() {
        let pads = [pad("A", 0x0079, 0x1843), pad("B", 0x057E, 0x2009)];
        let rules = generate_rules(&pads);
        assert_eq!(covered(&rules), [(0x0079, 0x1843), (0x057E, 0x2009)]);
    }

    #[test]
    fn a_pad_added_after_the_rules_were_written_is_reported_as_unhidden() {
        let installed = generate_rules(&[pad("Old", 0x0079, 0x1830)]);
        let now = [pad("Old", 0x0079, 0x1830), pad("New", 0x0079, 0x1843)];
        let missing = unhidden(&now, Some(&installed));
        assert_eq!(missing.len(), 1);
        assert_eq!(missing[0].name, "New");
    }

    #[test]
    fn no_rules_file_at_all_is_not_a_complaint() {
        assert!(unhidden(&[pad("A", 1, 2)], None).is_empty());
    }

    #[test]
    fn an_installed_file_covering_nothing_reports_every_pad() {
        assert_eq!(unhidden(&[pad("A", 1, 2)], Some("")).len(), 1);
    }

    #[test]
    fn a_damaged_rules_file_covers_what_can_still_be_read() {
        let rules = concat!(
            "SUBSYSTEM==\"input\", ATTRS{idVendor}==\"0079\", ",
            "ATTRS{idProduct}==\"1843\", ENV{ID_INPUT_JOYSTICK}=\"\"\n",
            "SUBSYSTEM==\"input\", ATTRS{idVendor}==\"zzzz\", ",
            "ATTRS{idProduct}==\"1830\"\n",
            "ATTRS{idVendor}==\"00\", ATTRS{idProduct}==\"11\"\n",
            "garbage\n",
        );
        assert_eq!(covered(rules), [(0x0079, 0x1843)]);
    }

    #[test]
    fn the_nix_snippet_lists_each_model_once_in_order() {
        let snippet = nix_module_snippet(&[
            pad("A", 0x0079, 0x1843),
            pad("B", 0x0079, 0x1843),
            pad("C", 0x057E, 0x2009),
            pad("D", 0, 0),
        ]);
        assert!(snippet.contains("\"0079:1843\""));
        assert!(snippet.contains("\"057e:2009\""));
        assert_eq!(snippet.matches("0079:1843").count(), 1);
        assert!(!snippet.contains("0000:0000"));
    }
}
