//! RetroArch's side of a mapping: the autoconfig lines it reads.

use std::collections::BTreeMap;

use crate::binding::{Binding, BindingKind};
use crate::control::{Control, CANONICAL_ORDER};

/// Analog stick half-axis stems, each with `_minus` and `_plus` binds.
pub const ANALOG_STEMS: [&str; 4] = ["input_l_x", "input_l_y", "input_r_x", "input_r_y"];

/// Drop axis binds shadowed by button binds on the opposite half.
pub fn drop_shadowed_axis_halves(lines: Vec<String>) -> Vec<String> {
    let key_of = |line: &str| line.split(" = ").next().unwrap_or("").to_owned();
    let keys: Vec<String> = lines
        .iter()
        .filter(|line| line.contains(" = "))
        .map(|line| key_of(line))
        .collect();

    let mut doomed: Vec<String> = Vec::new();
    for stem in ANALOG_STEMS {
        for (half, other) in [("minus", "plus"), ("plus", "minus")] {
            let button = format!("{stem}_{half}_btn");
            let axis = format!("{stem}_{other}_axis");
            if keys.contains(&button) && keys.contains(&axis) {
                doomed.push(axis);
            }
        }
    }
    if doomed.is_empty() {
        return lines;
    }
    lines
        .into_iter()
        .filter(|line| !doomed.contains(&key_of(line)))
        .collect()
}

/// Autoconfig entries for captured controls.
pub fn lines(
    bindings: &BTreeMap<Control, Binding>,
    overrides: &BTreeMap<Control, String>,
) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for control in CANONICAL_ORDER {
        let Some(binding) = bindings.get(&control) else {
            continue;
        };
        if !binding.retroarch_visible() {
            continue;
        }
        let Ok(target) = binding.retroarch() else {
            continue;
        };
        let key = match overrides.get(&control) {
            Some(override_key) if !override_key.is_empty() => override_key.clone(),
            _ => control.retroarch_key().to_owned(),
        };
        // Axis must use _axis key, not _btn (strtoull misparses signs).
        let key = if binding.kind == BindingKind::Axis {
            key.replace("_btn", "_axis")
        } else {
            key
        };
        out.push(format!("{key} = \"{target}\""));
    }
    drop_shadowed_axis_halves(out)
}

/// RetroArch's player slots.
pub const MAX_PLAYERS: u32 = 16;

/// `input_playerN_*` binds that RetroArch saves.
pub const PLAYER_BINDS: [&str; 24] = [
    "b",
    "y",
    "select",
    "start",
    "up",
    "down",
    "left",
    "right",
    "a",
    "x",
    "l",
    "r",
    "l2",
    "r2",
    "l3",
    "r3",
    "l_x_plus",
    "l_x_minus",
    "l_y_plus",
    "l_y_minus",
    "r_x_plus",
    "r_x_minus",
    "r_y_plus",
    "r_y_minus",
];

/// `input_playerN_device_reservation_type` values.
pub const RESERVATION_NONE: i32 = 0;
pub const RESERVATION_RESERVED: i32 = 2;

/// Reservation settings for all sixteen slots.
pub fn reservation_lines(managed: &[u32], virtual_name: impl Fn(u32) -> String) -> String {
    let mut lines = Vec::new();
    for player in 1..=MAX_PLAYERS {
        let reserved = managed.contains(&player);
        let name = if reserved {
            virtual_name(player)
        } else {
            String::new()
        };
        let kind = if reserved {
            RESERVATION_RESERVED
        } else {
            RESERVATION_NONE
        };
        lines.push(format!("input_player{player}_reserved_device = \"{name}\""));
        lines.push(format!(
            "input_player{player}_device_reservation_type = \"{kind}\""
        ));
    }
    lines.join("\n")
}

/// Config text pinning each player to its clone by name.
pub fn reservation_config(players: &[u32], virtual_name: impl Fn(u32) -> String) -> String {
    let mut sorted: Vec<u32> = players.to_vec();
    sorted.sort_unstable();
    let lines = [
        "# Generated by danstick. Pass to RetroArch with --appendconfig.",
        "# Players are pinned by device name, so pad enumeration order",
        "# no longer matters.",
        "",
        &reservation_lines(&sorted, virtual_name),
        "",
    ];
    lines.join("\n") + "\n"
}

/// What a launcher appends with `--appendconfig`: pinning, binds handed to the profiles, the keyboard.
pub fn appended_config(
    players: &[u32],
    seat: Option<u32>,
    virtual_name: impl Fn(u32) -> String,
) -> String {
    let mut seated: Vec<u32> = players
        .iter()
        .copied()
        .filter(|player| (1..=MAX_PLAYERS).contains(player))
        .collect();
    seated.sort_unstable();
    seated.dedup();
    let mut lines = vec![reservation_config(&seated, virtual_name)];
    lines.push("# A per-player bind in retroarch.cfg beats the autoconfig profile:".to_owned());
    lines.push("# RetroArch falls back to the profile only when the bind is `nul`.".to_owned());
    for player in &seated {
        for bind in PLAYER_BINDS {
            lines.push(format!("input_player{player}_{bind}_btn = \"nul\""));
            lines.push(format!("input_player{player}_{bind}_axis = \"nul\""));
        }
    }
    lines.push(String::new());
    lines.push(
        "# Appended settings are saved into retroarch.cfg on quit unless this is off,".to_owned(),
    );
    lines.push("# which is how stale reservations reach a session danstick is not in.".to_owned());
    lines.push("config_save_on_exit = \"false\"".to_owned());
    lines.join("\n") + "\n" + &keyboard_config(&seated, seat)
}

/// RetroArch's own keyboard defaults for one player, as suffix-less binds.
pub const KEYBOARD_DEFAULTS: [(&str, &str); 12] = [
    ("b", "z"),
    ("y", "a"),
    ("select", "rshift"),
    ("start", "enter"),
    ("up", "up"),
    ("down", "down"),
    ("left", "left"),
    ("right", "right"),
    ("a", "x"),
    ("x", "s"),
    ("l", "q"),
    ("r", "w"),
];

/// The desk's mouse: first in udev's pointer list, and RetroArch's own default for player 1.
pub const DESK_MOUSE: u32 = 0;

/// The first mouse index RetroArch has no device for, a cfg's only way to say a port has none.
pub const NO_MOUSE: u32 = 16;

/// Which mouse each port reads: the desk's for the keyboard's seat, none elsewhere.
pub fn mouse_config(keyboard: Option<u32>) -> Vec<String> {
    let mut lines = vec![
        String::new(),
        "# The desk's mouse belongs to the keyboard's seat: the person".to_owned(),
        "# sitting there has it under their other hand. RetroArch gives".to_owned(),
        "# port i mouse i by default, so every other port is sent past".to_owned(),
        "# the end of the pointer list, which is how a cfg says none.".to_owned(),
    ];
    for player in 1..=MAX_PLAYERS {
        let index = if keyboard == Some(player) {
            DESK_MOUSE
        } else {
            NO_MOUSE
        };
        lines.push(format!("input_player{player}_mouse_index = \"{index}\""));
    }
    lines
}

/// The keyboard's binds for the first port no managed pad holds, and the mouse beside it.
pub fn keyboard_config(managed: &[u32], seat: Option<u32>) -> String {
    let free = crate::keyboard::port(seat, managed, MAX_PLAYERS);
    if free == Some(1) {
        return mouse_config(free).join("\n") + "\n";
    }
    let mut lines = vec![
        String::new(),
        "# The keyboard takes the first port no pad holds. RetroArch".to_owned(),
        "# compiles it into player 1, so with that port seated the".to_owned(),
        "# keyboard's own binds move off it rather than doubling the pad.".to_owned(),
    ];
    for bind in PLAYER_BINDS {
        lines.push(format!("input_player1_{bind} = \"nul\""));
    }
    match free {
        Some(port) => {
            for (bind, key) in KEYBOARD_DEFAULTS {
                lines.push(format!("input_player{port}_{bind} = \"{key}\""));
            }
            lines.push(String::new());
            lines
                .push("# Without its player-1 binds the keyboard cannot drive the menu".to_owned());
            lines.push("# on its own; let every port do so, keyboard included.".to_owned());
            lines.push("input_all_users_control_menu = \"true\"".to_owned());
        }
        None => lines.push("# Every port is seated; the keyboard drives nobody.".to_owned()),
    }
    lines.extend(mouse_config(free));
    lines.join("\n") + "\n"
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::binding::RA_INVISIBLE;

    fn bindings(entries: &[(Control, Binding)]) -> BTreeMap<Control, Binding> {
        entries.iter().copied().collect()
    }

    #[test]
    fn a_captured_button_is_written_under_its_retroarch_key() {
        let out = lines(
            &bindings(&[(Control::A, Binding::button(1))]),
            &BTreeMap::new(),
        );
        assert_eq!(out, ["input_b_btn = \"1\""]);
    }

    #[test]
    fn an_uncaptured_control_gets_no_line_at_all() {
        let out = lines(&BTreeMap::new(), &BTreeMap::new());
        assert!(out.is_empty());
    }

    #[test]
    fn lines_come_out_in_canonical_order_whatever_order_they_went_in() {
        let out = lines(
            &bindings(&[
                (Control::Start, Binding::button(9)),
                (Control::A, Binding::button(1)),
                (Control::B, Binding::button(2)),
            ]),
            &BTreeMap::new(),
        );
        assert_eq!(
            out,
            [
                "input_b_btn = \"1\"",
                "input_a_btn = \"2\"",
                "input_start_btn = \"9\"",
            ]
        );
    }

    #[test]
    fn a_console_override_replaces_the_canonical_key() {
        let overrides: BTreeMap<Control, String> = [(Control::B, "input_y_btn".to_owned())]
            .into_iter()
            .collect();
        let out = lines(&bindings(&[(Control::B, Binding::button(2))]), &overrides);
        assert_eq!(out, ["input_y_btn = \"2\""]);
    }

    #[test]
    fn an_empty_override_falls_back_rather_than_writing_a_nameless_key() {
        let overrides: BTreeMap<Control, String> =
            [(Control::B, String::new())].into_iter().collect();
        let out = lines(&bindings(&[(Control::B, Binding::button(2))]), &overrides);
        assert_eq!(out, ["input_a_btn = \"2\""]);
    }

    #[test]
    fn an_axis_moves_to_the_axis_key_because_btn_misparses_the_sign() {
        let out = lines(
            &bindings(&[(Control::LeftTrigger, Binding::axis(2, -1))]),
            &BTreeMap::new(),
        );
        assert_eq!(out, ["input_l2_axis = \"-2\""]);
        assert!(
            !out[0].contains("_btn"),
            "strtoull would read -2 as button 2"
        );
    }

    #[test]
    fn a_button_retroarch_cannot_see_is_dropped_not_renumbered() {
        let out = lines(
            &bindings(&[
                (Control::A, Binding::button(1)),
                (
                    Control::B,
                    Binding::button(13).with_ra_index(Some(RA_INVISIBLE)),
                ),
            ]),
            &BTreeMap::new(),
        );
        assert_eq!(out, ["input_b_btn = \"1\""]);
    }

    #[test]
    fn a_hat_value_that_is_not_one_direction_is_dropped_not_fatal() {
        let out = lines(
            &bindings(&[
                (Control::A, Binding::button(1)),
                (Control::DpadUp, Binding::hat(0, 3)),
            ]),
            &BTreeMap::new(),
        );
        assert_eq!(out, ["input_b_btn = \"1\""]);
    }

    #[test]
    fn a_c_button_on_one_half_kills_the_axis_on_the_other() {
        let out = drop_shadowed_axis_halves(vec![
            "input_r_y_minus_btn = \"11\"".to_owned(),
            "input_r_y_plus_axis = \"+3\"".to_owned(),
            "input_l_x_minus_axis = \"-0\"".to_owned(),
        ]);
        assert_eq!(
            out,
            [
                "input_r_y_minus_btn = \"11\"",
                "input_l_x_minus_axis = \"-0\"",
            ],
            "the opposing axis must go, and nothing else"
        );
    }

    #[test]
    fn the_shadow_rule_works_in_both_directions() {
        let out = drop_shadowed_axis_halves(vec![
            "input_r_x_plus_btn = \"12\"".to_owned(),
            "input_r_x_minus_axis = \"-2\"".to_owned(),
        ]);
        assert_eq!(out, ["input_r_x_plus_btn = \"12\""]);
    }

    #[test]
    fn a_stick_with_axes_on_both_halves_is_left_alone() {
        let input = vec![
            "input_r_y_minus_axis = \"-3\"".to_owned(),
            "input_r_y_plus_axis = \"+3\"".to_owned(),
        ];
        assert_eq!(drop_shadowed_axis_halves(input.clone()), input);
    }

    #[test]
    fn a_stick_with_buttons_on_both_halves_is_left_alone() {
        let input = vec![
            "input_r_y_minus_btn = \"11\"".to_owned(),
            "input_r_y_plus_btn = \"12\"".to_owned(),
        ];
        assert_eq!(drop_shadowed_axis_halves(input.clone()), input);
    }

    #[test]
    fn a_line_with_no_separator_is_not_mistaken_for_a_key() {
        let input = vec!["# a comment".to_owned(), "input_b_btn = \"1\"".to_owned()];
        assert_eq!(drop_shadowed_axis_halves(input.clone()), input);
    }

    #[test]
    fn the_full_n64_c_button_capture_survives_end_to_end() {
        let out = lines(
            &bindings(&[
                (Control::A, Binding::button(1)),
                (Control::B, Binding::button(2)),
                (Control::RightStickUp, Binding::button(11)),
                (Control::RightStickDown, Binding::button(12)),
                (Control::RightStickLeft, Binding::button(13)),
                (Control::RightStickRight, Binding::button(14)),
            ]),
            &BTreeMap::new(),
        );
        assert_eq!(
            out,
            [
                "input_b_btn = \"1\"",
                "input_a_btn = \"2\"",
                "input_r_y_minus_btn = \"11\"",
                "input_r_y_plus_btn = \"12\"",
                "input_r_x_minus_btn = \"13\"",
                "input_r_x_plus_btn = \"14\"",
            ]
        );
    }
}
