//! udev rules that hide the physical pads, so only padmap's are enumerated.
//!
//! Anything reading controllers through udev -- RetroArch's joypad driver
//! filters on `ID_INPUT_JOYSTICK=1` -- sees the physical adapter *and* the
//! clone padmap made from it, and cannot tell which is which. Clearing that
//! property on the adapters padmap manages leaves only padmap's pads visible,
//! so indices become exactly 0..N-1 in the order the user assigned.
//!
//! A convenience, not a requirement, and it has a failure mode worth knowing:
//! while these rules are installed and padmap is *not* running, the hidden
//! adapters are invisible and there are no controllers at all. So the rules
//! name explicit vid/pid pairs rather than "all joysticks", and are undone by
//! deleting the file and reloading udev.
//!
//! EVIOCGRAB alone is not enough. Grabbing stops event *delivery* to other
//! readers, but the node stays in udev's enumeration, so a consumer still
//! counts it as a pad and gives it a port. Confirmed against a live run:
//! three grabbed physical pads plus two virtual ones produced five ports.

/// One controller, as much of it as a rule needs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Hideable {
    pub name: String,
    pub vid: u16,
    pub pid: u16,
}

const HEADER: &str = "\
# Generated by padmap. Do not edit; regenerate with `padmap hide`.
#
# Clears ID_INPUT_JOYSTICK on the adapters padmap republishes, so a udev
# joypad enumeration sees only padmap's virtual pads.
#
# While this file is installed and padmap is NOT running, these controllers
# are invisible. Undo by deleting this file and re-running
#   sudo udevadm control --reload-rules
#   sudo udevadm trigger --subsystem-match=input
";

/// udev rules hiding exactly these pads' parent devices.
pub fn generate_rules(pads: &[Hideable]) -> String {
    let mut out = String::from(HEADER);
    let mut seen: Vec<(u16, u16)> = Vec::new();
    for pad in pads {
        if pad.vid == 0 || pad.pid == 0 {
            // Without a vid/pid there is nothing safe to match on; matching by
            // name would be far too broad.
            out.push_str(&format!("# skipped {:?}: no usable vid/pid\n", pad.name));
            continue;
        }
        let key = (pad.vid, pad.pid);
        if seen.contains(&key) {
            continue;
        }
        seen.push(key);
        out.push_str(&format!("# {}\n", pad.name));
        out.push_str(&format!(
            "SUBSYSTEM==\"input\", ATTRS{{idVendor}}==\"{:04x}\", \
             ATTRS{{idProduct}}==\"{:04x}\", ENV{{ID_INPUT_JOYSTICK}}=\"\"\n",
            pad.vid, pad.pid
        ));
        // The same pad again, for when it arrives over Bluetooth.
        //
        // ATTRS{idVendor} walks up to a USB parent, and a Bluetooth pad has
        // none -- so the rule above silently covers nothing and the controller
        // stays visible. Not theoretical: a Switch Pro paired over Bluetooth
        // was enumerated alongside padmap's clone, both claiming 057e:2009,
        // and the game got the wrong one.
        //
        // Bluetooth HID devices hang off uhid and the directory name carries
        // the bus and ids, so this stays as narrow as the USB rule. It cannot
        // catch padmap's own pads: those are /devices/virtual/input/, with no
        // uhid anywhere in the path. Uppercase, as the kernel spells it.
        out.push_str(&format!(
            "SUBSYSTEM==\"input\", DEVPATH==\"*/uhid/0005:{:04X}:{:04X}.*\", \
             ENV{{ID_INPUT_JOYSTICK}}=\"\"\n",
            pad.vid, pad.pid
        ));
    }
    out
}

/// Every physical pad that must be hidden.
///
/// All of them, not just the ones holding a player slot right now. Which
/// controller is assigned changes every session; which adapters exist is a
/// property of the machine. Generating rules from the assignment is how an
/// installed file came to cover a Fightstick and a USB pad but not the
/// GameCube adapter plugged in later -- whose four ports then took player
/// slots 2 through 5.
///
/// It is also actively destructive to regenerate from the assignment: with one
/// controller assigned the result would *drop* the rules covering every other
/// adapter, un-hiding pads that were correctly hidden before. Union rather than
/// `discovered` alone, so a pad that is assigned but missing from the scan
/// still gets a rule.
pub fn targets(discovered: &[Hideable], assigned: &[Hideable]) -> Vec<Hideable> {
    let mut out = Vec::new();
    let mut seen: Vec<(u16, u16)> = Vec::new();
    for pad in discovered.iter().chain(assigned.iter()) {
        let key = (pad.vid, pad.pid);
        if pad.vid == 0 || pad.pid == 0 || seen.contains(&key) {
            continue;
        }
        seen.push(key);
        out.push(pad.clone());
    }
    out
}

/// The vid/pid pairs an installed rules file already covers.
///
/// Parsed out of the text rather than remembered from what was written, for
/// the usual reason: what is on disk is what udev applies, and a rebuild, a
/// reboot or an edit can all put those two out of step.
pub fn covered(rules: &str) -> Vec<(u16, u16)> {
    let mut out = Vec::new();
    // Deliberately not a regex: the shape is fixed and this has to agree with
    // what `generate_rules` writes, which is the only thing that writes it.
    for line in rules.lines() {
        let Some(vendor) = field_after(line, "ATTRS{idVendor}==\"") else {
            continue;
        };
        let Some(product) = field_after(line, "ATTRS{idProduct}==\"") else {
            continue;
        };
        if let (Ok(vid), Ok(pid)) = (
            u16::from_str_radix(&vendor, 16),
            u16::from_str_radix(&product, 16),
        ) {
            if !out.contains(&(vid, pid)) {
                out.push((vid, pid));
            }
        }
    }
    out
}

fn field_after(line: &str, marker: &str) -> Option<String> {
    let rest = line.split_once(marker)?.1;
    let value = rest.split_once('"')?.0;
    (value.len() == 4 && value.chars().all(|c| c.is_ascii_hexdigit())).then(|| value.to_owned())
}

/// Pads padmap republishes that the installed rules do not cover.
///
/// The rules are generated from whatever was plugged in at the time and then
/// left alone, so a controller bought afterwards is simply not in them.
/// Nothing notices: padmap goes on working, and a consumer quietly sees the
/// physical adapter *as well as* the virtual pad padmap made from it.
pub fn unhidden(pads: &[Hideable], rules: Option<&str>) -> Vec<Hideable> {
    // No rules installed at all is not this function's business to complain
    // about -- it is a setup step the user may simply not have taken.
    let Some(rules) = rules else {
        return Vec::new();
    };
    let covered = covered(rules);
    let mut out = Vec::new();
    let mut seen: Vec<(u16, u16)> = Vec::new();
    for pad in pads {
        let key = (pad.vid, pad.pid);
        if pad.vid == 0 || pad.pid == 0 || covered.contains(&key) || seen.contains(&key) {
            continue;
        }
        seen.push(key);
        out.push(pad.clone());
    }
    out
}

/// The declarative equivalent, for a system whose /etc is read-only.
pub fn nix_module_snippet(pads: &[Hideable]) -> String {
    let mut seen: Vec<(u16, u16)> = Vec::new();
    for pad in pads {
        let key = (pad.vid, pad.pid);
        if pad.vid != 0 && pad.pid != 0 && !seen.contains(&key) {
            seen.push(key);
        }
    }
    let entries: Vec<String> = seen
        .iter()
        .map(|(vid, pid)| format!("      \"{vid:04x}:{pid:04x}\""))
        .collect();
    format!(
        "  programs.padmap = {{\n    enable = true;\n    hideDevices = [\n{}\n    ];\n  }};",
        entries.join("\n")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pad(name: &str, vid: u16, pid: u16) -> Hideable {
        Hideable {
            name: name.to_owned(),
            vid,
            pid,
        }
    }

    #[test]
    fn each_pad_gets_a_usb_rule_and_a_bluetooth_rule() {
        // ATTRS{idVendor} walks up to a USB parent and a Bluetooth pad has
        // none, so the USB rule alone silently covers nothing over Bluetooth.
        let rules = generate_rules(&[pad("Switch Pro", 0x057E, 0x2009)]);
        assert!(rules.contains(r#"ATTRS{idVendor}=="057e""#));
        assert!(rules.contains(r#"ATTRS{idProduct}=="2009""#));
        assert!(rules.contains(r#"DEVPATH=="*/uhid/0005:057E:2009.*""#));
        assert_eq!(
            rules.matches("ID_INPUT_JOYSTICK").count(),
            3,
            "two rules plus the header"
        );
    }

    #[test]
    fn the_bluetooth_rule_is_uppercase_because_the_kernel_spells_it_that_way() {
        let rules = generate_rules(&[pad("Pad", 0x28de, 0x11ff)]);
        assert!(rules.contains("0005:28DE:11FF."), "{rules}");
        assert!(
            rules.contains(r#"=="28de""#),
            "the USB rule stays lowercase"
        );
    }

    #[test]
    fn a_pad_with_no_ids_is_skipped_and_said_so_rather_than_matched_by_name() {
        let rules = generate_rules(&[pad("Nameless", 0, 0)]);
        assert!(rules.contains("no usable vid/pid"));
        assert!(!rules.contains("ATTRS{idVendor}"));
    }

    #[test]
    fn the_same_model_twice_produces_one_pair_of_rules() {
        // Four ports of one adapter are one device to udev.
        let pads: Vec<Hideable> = (0..4).map(|_| pad("Mayflash", 0x0079, 0x1843)).collect();
        let rules = generate_rules(&pads);
        assert_eq!(rules.matches("ATTRS{idVendor}").count(), 1);
    }

    #[test]
    fn targets_are_the_union_and_not_just_what_is_assigned() {
        // Regenerating from the assignment would drop the rules covering every
        // other adapter, un-hiding pads that were correctly hidden before.
        let discovered = [pad("A", 1, 2), pad("B", 3, 4)];
        let assigned = [pad("B", 3, 4), pad("C", 5, 6)];
        let result = targets(&discovered, &assigned);
        assert_eq!(
            result.iter().map(|p| (p.vid, p.pid)).collect::<Vec<_>>(),
            [(1, 2), (3, 4), (5, 6)]
        );
    }

    #[test]
    fn a_pad_with_no_ids_is_never_a_target() {
        assert!(targets(&[pad("X", 0, 0)], &[]).is_empty());
        assert!(targets(&[pad("X", 1, 0)], &[]).is_empty());
    }

    #[test]
    fn what_was_generated_is_read_back_as_covered() {
        // The only writer and the only reader of this file are these two
        // functions, so a disagreement between them is the whole failure.
        let pads = [pad("A", 0x0079, 0x1843), pad("B", 0x057E, 0x2009)];
        let rules = generate_rules(&pads);
        assert_eq!(covered(&rules), [(0x0079, 0x1843), (0x057E, 0x2009)]);
    }

    #[test]
    fn a_pad_added_after_the_rules_were_written_is_reported_as_unhidden() {
        let installed = generate_rules(&[pad("Old", 0x0079, 0x1830)]);
        let now = [pad("Old", 0x0079, 0x1830), pad("New", 0x0079, 0x1843)];
        let missing = unhidden(&now, Some(&installed));
        assert_eq!(missing.len(), 1);
        assert_eq!(missing[0].name, "New");
    }

    #[test]
    fn no_rules_file_at_all_is_not_a_complaint() {
        // A setup step the user may simply not have taken.
        assert!(unhidden(&[pad("A", 1, 2)], None).is_empty());
    }

    #[test]
    fn an_installed_file_covering_nothing_reports_every_pad() {
        // Different from "no file": an empty installed file must not read as
        // though everything were hidden.
        assert_eq!(unhidden(&[pad("A", 1, 2)], Some("")).len(), 1);
    }

    #[test]
    fn a_damaged_rules_file_covers_what_can_still_be_read() {
        let rules = concat!(
            "SUBSYSTEM==\"input\", ATTRS{idVendor}==\"0079\", ",
            "ATTRS{idProduct}==\"1843\", ENV{ID_INPUT_JOYSTICK}=\"\"\n",
            "SUBSYSTEM==\"input\", ATTRS{idVendor}==\"zzzz\", ",
            "ATTRS{idProduct}==\"1830\"\n",
            "ATTRS{idVendor}==\"00\", ATTRS{idProduct}==\"11\"\n",
            "garbage\n",
        );
        assert_eq!(covered(rules), [(0x0079, 0x1843)]);
    }

    #[test]
    fn the_nix_snippet_lists_each_model_once_in_order() {
        let snippet = nix_module_snippet(&[
            pad("A", 0x0079, 0x1843),
            pad("B", 0x0079, 0x1843),
            pad("C", 0x057E, 0x2009),
            pad("D", 0, 0),
        ]);
        assert!(snippet.contains("\"0079:1843\""));
        assert!(snippet.contains("\"057e:2009\""));
        assert_eq!(snippet.matches("0079:1843").count(), 1);
        assert!(!snippet.contains("0000:0000"));
    }
}
