//! RetroArch's side of a mapping: the autoconfig lines it reads.

use std::collections::BTreeMap;

use crate::binding::{Binding, BindingKind};
use crate::control::{Control, CANONICAL_ORDER};

/// Analog stick half-axis stems, each with `_minus` and `_plus` binds.
pub const ANALOG_STEMS: [&str; 4] = ["input_l_x", "input_l_y", "input_r_x", "input_r_y"];

/// Drop axis binds shadowed by button binds on the opposite half.
pub fn drop_shadowed_axis_halves(lines: Vec<String>) -> Vec<String> {
    let key_of = |line: &str| line.split(" = ").next().unwrap_or("").to_owned();
    let keys: Vec<String> = lines
        .iter()
        .filter(|line| line.contains(" = "))
        .map(|line| key_of(line))
        .collect();

    let mut doomed: Vec<String> = Vec::new();
    for stem in ANALOG_STEMS {
        for (half, other) in [("minus", "plus"), ("plus", "minus")] {
            let button = format!("{stem}_{half}_btn");
            let axis = format!("{stem}_{other}_axis");
            if keys.contains(&button) && keys.contains(&axis) {
                doomed.push(axis);
            }
        }
    }
    if doomed.is_empty() {
        return lines;
    }
    lines
        .into_iter()
        .filter(|line| !doomed.contains(&key_of(line)))
        .collect()
}

/// Autoconfig entries for captured controls.
pub fn lines(
    bindings: &BTreeMap<Control, Binding>,
    overrides: &BTreeMap<Control, String>,
) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for control in CANONICAL_ORDER {
        let Some(binding) = bindings.get(&control) else {
            continue;
        };
        if !binding.retroarch_visible() {
            continue;
        }
        let Ok(target) = binding.retroarch() else {
            continue;
        };
        let key = match overrides.get(&control) {
            Some(override_key) if !override_key.is_empty() => override_key.clone(),
            _ => control.retroarch_key().to_owned(),
        };
        // Axis must use _axis key, not _btn (strtoull misparses signs).
        let key = if binding.kind == BindingKind::Axis {
            key.replace("_btn", "_axis")
        } else {
            key
        };
        out.push(format!("{key} = \"{target}\""));
    }
    drop_shadowed_axis_halves(out)
}

/// RetroArch's player slots.
pub const MAX_PLAYERS: u32 = 16;

/// `input_playerN_device_reservation_type` values.
pub const RESERVATION_NONE: i32 = 0;
pub const RESERVATION_RESERVED: i32 = 2;

/// Vacant pad indices for unmanaged slots.
pub fn empty_indices(pad_count: usize, wanted: usize) -> Vec<usize> {
    let ceiling = MAX_PLAYERS as usize - 1;
    (0..wanted).map(|n| (pad_count + n).min(ceiling)).collect()
}

/// Player -> the pad index RetroArch's udev driver will give its clone.
pub fn compute_pad_indices(
    virtual_paths: &BTreeMap<u32, String>,
    order: &BTreeMap<usize, String>,
) -> BTreeMap<u32, usize> {
    let by_path: BTreeMap<&str, usize> = order
        .iter()
        .map(|(index, path)| (path.as_str(), *index))
        .collect();
    virtual_paths
        .iter()
        .filter_map(|(player, path)| by_path.get(path.as_str()).map(|index| (*player, *index)))
        .collect()
}

/// Player -> pad index, for the players padmap is actually binding.
pub fn managed_players(
    players: &[u32],
    virtual_paths: &BTreeMap<u32, String>,
    order: &BTreeMap<usize, String>,
) -> BTreeMap<u32, usize> {
    let indices = compute_pad_indices(virtual_paths, order);
    players
        .iter()
        .filter_map(|player| indices.get(player).map(|index| (*player, *index)))
        .collect()
}

/// Reservation settings for all sixteen slots.
pub fn reservation_lines(managed: &[u32], virtual_name: impl Fn(u32) -> String) -> String {
    let mut lines = Vec::new();
    for player in 1..=MAX_PLAYERS {
        let reserved = managed.contains(&player);
        let name = if reserved {
            virtual_name(player)
        } else {
            String::new()
        };
        let kind = if reserved {
            RESERVATION_RESERVED
        } else {
            RESERVATION_NONE
        };
        lines.push(format!("input_player{player}_reserved_device = \"{name}\""));
        lines.push(format!(
            "input_player{player}_device_reservation_type = \"{kind}\""
        ));
    }
    lines.join("\n")
}

/// Config text pinning each player to its clone by name.
pub fn reservation_config(players: &[u32], virtual_name: impl Fn(u32) -> String) -> String {
    let mut sorted: Vec<u32> = players.to_vec();
    sorted.sort_unstable();
    let lines = [
        "# Generated by padmap. Pass to RetroArch with --appendconfig.",
        "# Players are pinned by device name, so pad enumeration order",
        "# no longer matters.",
        "",
        &reservation_lines(&sorted, virtual_name),
        "",
    ];
    lines.join("\n") + "\n"
}

/// Flags to empty core ports with no assigned players.
pub fn launch_args(
    players: &[u32],
    virtual_paths: &BTreeMap<u32, String>,
    order: &BTreeMap<usize, String>,
) -> Vec<String> {
    let managed = managed_players(players, virtual_paths, order);
    (1..=MAX_PLAYERS)
        .filter(|player| !managed.contains_key(player))
        .flat_map(|player| ["--nodevice".to_owned(), player.to_string()])
        .collect()
}

/// Keys identifying a pad in a profile, not button binds.
pub const IDENTITY_KEYS: [&str; 5] = [
    "input_device",
    "input_device_display_name",
    "input_vendor_id",
    "input_product_id",
    "input_phys",
];

/// Profile for a clone with button mapping from a libretro profile.
pub fn derive_profile(
    source: Option<(&str, &[(String, String)])>,
    player: u32,
    vid: u16,
    pid: u16,
    virtual_name: impl Fn(u32) -> String,
) -> String {
    let name = virtual_name(player);
    let mut out = vec![
        format!("# Generated by padmap for {name}."),
        format!(
            "# Button mapping copied from: {}",
            source.map(|(file, _)| file).unwrap_or("<none found>")
        ),
        "input_driver = \"udev\"".to_owned(),
        format!("input_device = \"{name}\""),
        format!("input_device_display_name = \"{name}\""),
        format!("input_vendor_id = \"{vid}\""),
        format!("input_product_id = \"{pid}\""),
    ];
    if let Some((_, values)) = source {
        for (key, value) in values {
            if IDENTITY_KEYS.contains(&key.as_str()) || key == "input_driver" {
                continue;
            }
            out.push(format!("{key} = \"{value}\""));
        }
    }
    out.join("\n") + "\n"
}

/// Facts for the launch override.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct LaunchFacts {
    /// Whether every managed pad is calibrated.
    pub all_calibrated: bool,
    /// Path to padmap's autoconfig profiles.
    pub autoconfig_dir: String,
    /// Enable verbose logging.
    pub verbose: bool,
}

/// Full override config passed to RetroArch via `--appendconfig`.
pub fn launch_config(
    players: &[u32],
    virtual_paths: &BTreeMap<u32, String>,
    order: &BTreeMap<usize, String>,
    facts: &LaunchFacts,
    virtual_name: impl Fn(u32) -> String,
) -> String {
    let mut managed = managed_players(players, virtual_paths, order);
    managed.retain(|player, _| (1..=MAX_PLAYERS).contains(player));
    let mut dropped: Vec<u32> = players
        .iter()
        .copied()
        .filter(|player| !managed.contains_key(player))
        .collect();
    dropped.sort_unstable();
    let managed_sorted: Vec<u32> = managed.keys().copied().collect();

    let mut lines: Vec<String> = vec![
        "# Generated by padmap. Passed to RetroArch with --appendconfig.".to_owned(),
        "# Regenerated at every launch, since pad indices depend on what is".to_owned(),
        "# currently plugged in.".to_owned(),
        "#".to_owned(),
        format!(
            "# {} of {MAX_PLAYERS} player slots are assigned; the rest",
            managed.len()
        ),
        "# are explicitly emptied rather than left to retroarch.cfg.".to_owned(),
    ];
    for player in &dropped {
        lines.push(format!(
            "# player {player}: virtual pad not in the enumeration, emptied"
        ));
    }

    lines.push(String::new());
    lines.push("# Primary binding: explicit pad indices, computed from the".to_owned());
    lines.push("# live udev enumeration order.".to_owned());
    let mut spare = empty_indices(order.len(), MAX_PLAYERS as usize - managed.len()).into_iter();
    for player in 1..=MAX_PLAYERS {
        let index = match managed.get(&player) {
            Some(index) => *index,
            // Never runs dry: exactly one spare per unmanaged slot, by construction above.
            None => spare.next().unwrap_or(MAX_PLAYERS as usize - 1),
        };
        lines.push(format!("input_player{player}_joypad_index = \"{index}\""));
    }

    lines.push(String::new());
    lines.push("# Secondary binding: reservation by the unique names we".to_owned());
    lines.push("# gave the virtual pads, which does not depend on ordering.".to_owned());
    lines.push("# Unmanaged slots have theirs cleared, so a reservation left".to_owned());
    lines.push("# over from a session with more players cannot hold a slot".to_owned());
    lines.push("# open for a virtual pad that no longer exists.".to_owned());
    lines.push(reservation_lines(&managed_sorted, &virtual_name));

    lines.push(String::new());
    lines.push("# Hand the managed players back to autoconfig.".to_owned());
    lines.push("#".to_owned());
    lines.push("# A per-player bind in retroarch.cfg beats the autoconfig".to_owned());
    lines.push("# profile -- RetroArch only falls back to the profile when".to_owned());
    lines.push("# the explicit bind is `nul`. Leftovers there make a pad".to_owned());
    lines.push("# report as configured while the buttons do nothing.".to_owned());
    lines.push("# Only managed slots: an unmanaged one has no pad, so what".to_owned());
    lines.push("# its binds say cannot matter.".to_owned());
    for player in &managed_sorted {
        for bind in crate::userconfig::PLAYER_BINDS {
            lines.push(format!("input_player{player}_{bind}_btn = \"nul\""));
            lines.push(format!("input_player{player}_{bind}_axis = \"nul\""));
        }
    }

    if !managed.is_empty() && facts.all_calibrated {
        lines.push(String::new());
        lines.push("# Every managed pad is calibrated, so padmap is already".to_owned());
        lines.push("# delivering the stick's full range. Gain on top of that".to_owned());
        lines.push("# only saturates it early.".to_owned());
        lines.push("input_analog_sensitivity = \"1.000000\"".to_owned());
    }

    lines.push(String::new());
    lines.push("# Autoconfig comes from padmap's own directory, not".to_owned());
    lines.push("# libretro's database. RetroArch scans exactly one, and".to_owned());
    lines.push("# the database was both outscoring these profiles and".to_owned());
    lines.push("# binding controls the user never mapped.".to_owned());
    lines.push(format!(
        "joypad_autoconfig_dir = \"{}\"",
        facts.autoconfig_dir
    ));

    lines.push(String::new());
    lines.push("# Core-side ports are NOT set here. input_libretro_device_pN".to_owned());
    lines.push("# looks like the setting for it and is silently ignored from".to_owned());
    lines.push("# a config file -- see launch_args(), which does the job on".to_owned());
    lines.push("# the command line instead.".to_owned());

    lines.push(String::new());
    lines.push("# --appendconfig is merged into the live config, and with".to_owned());
    lines.push("# config_save_on_exit the whole merged result is written".to_owned());
    lines.push("# back to retroarch.cfg on quit. That is how the stale".to_owned());
    lines.push("# reservations and duplicate joypad indices this file now".to_owned());
    lines.push("# has to override got there in the first place. Turning it".to_owned());
    lines.push("# off is what actually makes the override per-launch.".to_owned());
    lines.push("config_save_on_exit = \"false\"".to_owned());

    if facts.verbose {
        lines.push(String::new());
        lines.push("# Diagnostics, enabled by `padmap launch --log`.".to_owned());
        lines.push("log_verbosity = \"true\"".to_owned());
        lines.push("frontend_log_level = \"0\"".to_owned());
    }

    lines.push(String::new());
    lines.join("\n") + "\n"
}

/// RetroArch's own keyboard defaults for one player, as suffix-less binds.
/// From `config.def.keybinds.h`; only player 1 has them compiled in.
pub const KEYBOARD_DEFAULTS: [(&str, &str); 12] = [
    ("b", "z"),
    ("y", "a"),
    ("select", "rshift"),
    ("start", "enter"),
    ("up", "up"),
    ("down", "down"),
    ("left", "left"),
    ("right", "right"),
    ("a", "x"),
    ("x", "s"),
    ("l", "q"),
    ("r", "w"),
];

/// The desk's mouse: first in udev's pointer list, and RetroArch's own
/// default for player 1.
pub const DESK_MOUSE: u32 = 0;

/// The first mouse index RetroArch has no device for: `udev_get_mouse` reads
/// `pointers[index]` only while `index < MAX_INPUT_DEVICES` (16), else leaves
/// `dev_index` at -1 -- a cfg's only way to say a port has no mouse.
pub const NO_MOUSE: u32 = 16;

/// Which mouse each port reads: the desk's for the keyboard's seat, none
/// elsewhere. RetroArch seeds `input_mouse_index[i] = i`, so player 1 holds
/// the desk's mouse whoever sits there; every port is written rather than
/// only the ones that differ, because `--appendconfig` merges into a live
/// config that may still carry a stale index from an earlier session.
pub fn mouse_config(keyboard: Option<u32>) -> Vec<String> {
    let mut lines = vec![
        String::new(),
        "# The desk's mouse belongs to the keyboard's seat: the person".to_owned(),
        "# sitting there has it under their other hand. RetroArch gives".to_owned(),
        "# port i mouse i by default, so every other port is sent past".to_owned(),
        "# the end of the pointer list, which is how a cfg says none.".to_owned(),
    ];
    for player in 1..=MAX_PLAYERS {
        let index = if keyboard == Some(player) {
            DESK_MOUSE
        } else {
            NO_MOUSE
        };
        lines.push(format!("input_player{player}_mouse_index = \"{index}\""));
    }
    lines
}

/// The keyboard's binds for the first port no managed pad holds, and the
/// mouse that sits beside it.
///
/// RetroArch compiles the keyboard into player 1 only, independent of
/// whatever pad also binds that port, so a pad seated there needs the
/// keyboard's defaults nulled and rewritten on the port it moved to. The
/// mouse indices are written either way: the keys' defaults agree with
/// padmap when the keyboard is player 1 and the mice's do not.
pub fn keyboard_config(managed: &[u32], seat: Option<u32>) -> String {
    let free = crate::keyboard::port(seat, managed, MAX_PLAYERS);
    if free == Some(1) {
        return mouse_config(free).join("\n") + "\n";
    }
    let mut lines = vec![
        String::new(),
        "# The keyboard takes the first port no pad holds. RetroArch".to_owned(),
        "# compiles it into player 1, so with that port seated the".to_owned(),
        "# keyboard's own binds move off it rather than doubling the pad.".to_owned(),
    ];
    for bind in crate::userconfig::PLAYER_BINDS {
        lines.push(format!("input_player1_{bind} = \"nul\""));
    }
    match free {
        Some(port) => {
            for (bind, key) in KEYBOARD_DEFAULTS {
                lines.push(format!("input_player{port}_{bind} = \"{key}\""));
            }
            lines.push(String::new());
            lines
                .push("# Without its player-1 binds the keyboard cannot drive the menu".to_owned());
            lines.push("# on its own; let every port do so, keyboard included.".to_owned());
            lines.push("input_all_users_control_menu = \"true\"".to_owned());
        }
        None => lines.push("# Every port is seated; the keyboard drives nobody.".to_owned()),
    }
    lines.extend(mouse_config(free));
    lines.join("\n") + "\n"
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::binding::RA_INVISIBLE;

    fn bindings(entries: &[(Control, Binding)]) -> BTreeMap<Control, Binding> {
        entries.iter().copied().collect()
    }

    #[test]
    fn a_captured_button_is_written_under_its_retroarch_key() {
        let out = lines(
            &bindings(&[(Control::A, Binding::button(1))]),
            &BTreeMap::new(),
        );
        assert_eq!(out, ["input_b_btn = \"1\""]);
    }

    #[test]
    fn an_uncaptured_control_gets_no_line_at_all() {
        let out = lines(&BTreeMap::new(), &BTreeMap::new());
        assert!(out.is_empty());
    }

    #[test]
    fn lines_come_out_in_canonical_order_whatever_order_they_went_in() {
        let out = lines(
            &bindings(&[
                (Control::Start, Binding::button(9)),
                (Control::A, Binding::button(1)),
                (Control::B, Binding::button(2)),
            ]),
            &BTreeMap::new(),
        );
        assert_eq!(
            out,
            [
                "input_b_btn = \"1\"",
                "input_a_btn = \"2\"",
                "input_start_btn = \"9\"",
            ]
        );
    }

    #[test]
    fn a_console_override_replaces_the_canonical_key() {
        let overrides: BTreeMap<Control, String> = [(Control::B, "input_y_btn".to_owned())]
            .into_iter()
            .collect();
        let out = lines(&bindings(&[(Control::B, Binding::button(2))]), &overrides);
        assert_eq!(out, ["input_y_btn = \"2\""]);
    }

    #[test]
    fn an_empty_override_falls_back_rather_than_writing_a_nameless_key() {
        let overrides: BTreeMap<Control, String> =
            [(Control::B, String::new())].into_iter().collect();
        let out = lines(&bindings(&[(Control::B, Binding::button(2))]), &overrides);
        assert_eq!(out, ["input_a_btn = \"2\""]);
    }

    #[test]
    fn an_axis_moves_to_the_axis_key_because_btn_misparses_the_sign() {
        let out = lines(
            &bindings(&[(Control::LeftTrigger, Binding::axis(2, -1))]),
            &BTreeMap::new(),
        );
        assert_eq!(out, ["input_l2_axis = \"-2\""]);
        assert!(
            !out[0].contains("_btn"),
            "strtoull would read -2 as button 2"
        );
    }

    #[test]
    fn a_button_retroarch_cannot_see_is_dropped_not_renumbered() {
        let out = lines(
            &bindings(&[
                (Control::A, Binding::button(1)),
                (
                    Control::B,
                    Binding::button(13).with_ra_index(Some(RA_INVISIBLE)),
                ),
            ]),
            &BTreeMap::new(),
        );
        assert_eq!(out, ["input_b_btn = \"1\""]);
    }

    #[test]
    fn a_hat_value_that_is_not_one_direction_is_dropped_not_fatal() {
        let out = lines(
            &bindings(&[
                (Control::A, Binding::button(1)),
                (Control::DpadUp, Binding::hat(0, 3)),
            ]),
            &BTreeMap::new(),
        );
        assert_eq!(out, ["input_b_btn = \"1\""]);
    }

    #[test]
    fn a_c_button_on_one_half_kills_the_axis_on_the_other() {
        let out = drop_shadowed_axis_halves(vec![
            "input_r_y_minus_btn = \"11\"".to_owned(),
            "input_r_y_plus_axis = \"+3\"".to_owned(),
            "input_l_x_minus_axis = \"-0\"".to_owned(),
        ]);
        assert_eq!(
            out,
            [
                "input_r_y_minus_btn = \"11\"",
                "input_l_x_minus_axis = \"-0\"",
            ],
            "the opposing axis must go, and nothing else"
        );
    }

    #[test]
    fn the_shadow_rule_works_in_both_directions() {
        let out = drop_shadowed_axis_halves(vec![
            "input_r_x_plus_btn = \"12\"".to_owned(),
            "input_r_x_minus_axis = \"-2\"".to_owned(),
        ]);
        assert_eq!(out, ["input_r_x_plus_btn = \"12\""]);
    }

    #[test]
    fn a_stick_with_axes_on_both_halves_is_left_alone() {
        let input = vec![
            "input_r_y_minus_axis = \"-3\"".to_owned(),
            "input_r_y_plus_axis = \"+3\"".to_owned(),
        ];
        assert_eq!(drop_shadowed_axis_halves(input.clone()), input);
    }

    #[test]
    fn a_stick_with_buttons_on_both_halves_is_left_alone() {
        let input = vec![
            "input_r_y_minus_btn = \"11\"".to_owned(),
            "input_r_y_plus_btn = \"12\"".to_owned(),
        ];
        assert_eq!(drop_shadowed_axis_halves(input.clone()), input);
    }

    #[test]
    fn a_line_with_no_separator_is_not_mistaken_for_a_key() {
        let input = vec!["# a comment".to_owned(), "input_b_btn = \"1\"".to_owned()];
        assert_eq!(drop_shadowed_axis_halves(input.clone()), input);
    }

    #[test]
    fn the_full_n64_c_button_capture_survives_end_to_end() {
        let out = lines(
            &bindings(&[
                (Control::A, Binding::button(1)),
                (Control::B, Binding::button(2)),
                (Control::RightStickUp, Binding::button(11)),
                (Control::RightStickDown, Binding::button(12)),
                (Control::RightStickLeft, Binding::button(13)),
                (Control::RightStickRight, Binding::button(14)),
            ]),
            &BTreeMap::new(),
        );
        assert_eq!(
            out,
            [
                "input_b_btn = \"1\"",
                "input_a_btn = \"2\"",
                "input_r_y_minus_btn = \"11\"",
                "input_r_y_plus_btn = \"12\"",
                "input_r_x_minus_btn = \"13\"",
                "input_r_x_plus_btn = \"14\"",
            ]
        );
    }
}
