"""Does starting Pegasus replace a daemon that is running older code?

The failure this guards against has no symptom until much later. `padmap
serve` holds the modules it was started with, so after a rebuild it keeps
serving the previous version -- still answering the socket, still writing a
launch.cfg that looks entirely plausible, just generated by the old code. A
controller-port bug that was genuinely fixed went on reproducing for exactly
this reason, and nothing on disk showed why.

The Pegasus wrapper therefore runs `padmap ensure-daemon` before starting the
front-end. This checks that it works, against the real wrapper:

  1. start a daemon that claims an obviously stale build id
  2. run the real entry point -- the Pegasus wrapper, or padmap-start
  3. the daemon should have been replaced by one reporting the store build

Both entry points are covered, because they reach the check by different
routes: the Pegasus wrapper calls it itself (which is what protects a start
from a session manager or .desktop file), while padmap-start calls it and
then tells Pegasus to skip its own.

Runs entirely inside a temporary XDG_RUNTIME_DIR, so the daemon under test is
a separate one on a separate socket and your real daemon is untouched. The
stale daemon is started without any assignments, so it grabs no pads.

    python3 tools/e2e_daemon.py [--entry pegasus|start] [--keep]

Needs Xvfb; nothing appears on your screen.
"""

import argparse
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

STALE_ID = "stale-build-for-e2e-daemon-test"


def pick_display() -> int:
    """First display number with no X lock file.

    Not a fixed number: Xvfb's lock outlives the process by a moment, so two
    of these tools run back to back would collide and the second would fail
    for a reason that has nothing to do with what it tests.
    """
    for number in range(90, 130):
        if not Path(f"/tmp/.X{number}-lock").exists():
            return number
    raise SystemExit("no free X display between :90 and :129")


DISPLAY_NUM = pick_display()


def build(attr: str) -> str:
    out = subprocess.run(
        ["nix", "build", "--no-link", "--print-out-paths", f".#{attr}"],
        cwd=REPO, capture_output=True, text=True,
    )
    if out.returncode != 0:
        raise SystemExit(f"nix build .#{attr} failed:\n{out.stderr}")
    return out.stdout.strip().splitlines()[-1]


def daemon_state(sock_path: Path, timeout: float = 1.0) -> dict | None:
    from padmap import protocol

    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        sock.settimeout(timeout)
        sock.connect(str(sock_path))
        sock.sendall(protocol.encode({"cmd": "status"}))
        reader = protocol.LineReader()
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            try:
                data = sock.recv(65536)
            except (TimeoutError, OSError):
                break
            if not data:
                break
            for message in reader.feed(data):
                if message.get("event") == "state":
                    return message
        return None
    except OSError:
        return None
    finally:
        sock.close()


def wait_for(sock_path: Path, seconds: float) -> dict | None:
    deadline = time.monotonic() + seconds
    while time.monotonic() < deadline:
        state = daemon_state(sock_path)
        if state is not None:
            return state
        time.sleep(0.2)
    return None


def write_theme(config: Path) -> None:
    """A theme that quits as soon as it loads.

    The point of the run is the wrapper's pre-launch check, which has already
    happened by the time any QML evaluates, so there is nothing to wait for.
    """
    theme = config / "pegasus-frontend" / "themes" / "quit"
    theme.mkdir(parents=True, exist_ok=True)
    (theme / "theme.cfg").write_text(
        "name: quit\nauthor: padmap\nqmlpath: theme.qml\n")
    (theme / "theme.qml").write_text("""
import QtQuick 2.0

FocusScope {
    focus: true
    Timer {
        interval: 1200; running: true; repeat: false
        onTriggered: { console.log("E2E: theme loaded, quitting"); Qt.quit(); }
    }
}
""")
    (config / "pegasus-frontend" / "settings.txt").write_text(
        "general.theme: themes/quit/\ngeneral.fullscreen: false\n")
    (config / "pegasus-frontend" / "game_dirs.txt").write_text("")


class xvfb:
    def __enter__(self):
        self.proc = subprocess.Popen(
            ["nix", "shell", "nixpkgs#xvfb", "--command",
             "Xvfb", f":{DISPLAY_NUM}", "-screen", "0", "800x600x24"],
            cwd=REPO, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        time.sleep(4)
        return self

    def __exit__(self, *_exc):
        self.proc.terminate()
        try:
            self.proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            self.proc.kill()


def real_daemon_pid() -> int | None:
    """Pid of a daemon on the user's actual XDG_RUNTIME_DIR, if any."""
    real = Path(os.environ.get("XDG_RUNTIME_DIR", "/tmp")) / "padmap"
    state = daemon_state(real / "padmap.sock", timeout=1.0)
    if state is None:
        return None
    pid = state.get("pid")
    return pid if isinstance(pid, int) else None


def alive(pid: int) -> bool:
    return Path(f"/proc/{pid}").exists()


def _terminate_tree(proc: subprocess.Popen) -> None:
    """Take down a process and anything it spawned in its session."""
    if proc.poll() is not None:
        return
    for sig in (15, 9):
        try:
            os.killpg(os.getpgid(proc.pid), sig)
        except OSError:
            return
        try:
            proc.wait(timeout=5)
            return
        except subprocess.TimeoutExpired:
            continue


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--entry", choices=("pegasus", "start"), default="pegasus",
        help="which entry point to exercise. Both must work: 'pegasus' is "
             "the wrapper a session manager or .desktop file invokes, "
             "'start' is padmap-start, and they check the daemon by "
             "different routes.")
    parser.add_argument("--keep", action="store_true")
    parser.add_argument(
        "--skip-check", action="store_true",
        help="set PADMAP_SKIP_DAEMON_CHECK=1, disabling the wrapper's check. "
             "The test must FAIL with this; that is what proves it is "
             "observing the check and not something incidental.")
    args = parser.parse_args()

    print("building...")
    build("padmap")  # built for its runtime deps
    if args.entry == "start":
        entry = build("padmap-start") + "/bin/padmap-start"
    else:
        entry = build("pegasus") + "/bin/pegasus-fe"
    print(f"  entry point ({args.entry}): {entry}")

    # A daemon on the *real* runtime dir, if the user has one. Restarting is
    # scoped to the socket it was asked about, so this must survive untouched.
    # It did not always: an earlier _stop_daemon matched on the command line
    # and killed every padmap daemon the user had, which this now catches.
    bystander = real_daemon_pid()
    if bystander is not None:
        print(f"  bystander daemon on the real runtime dir: pid {bystander}")

    root = Path(tempfile.mkdtemp(prefix="padmap-daemon-"))
    stale = None
    try:
        runtime = root / "run"
        (runtime / "padmap").mkdir(parents=True, exist_ok=True)
        runtime.chmod(0o700)
        sock_path = runtime / "padmap" / "padmap.sock"

        config = root / "config"
        write_theme(config)

        # Deliberately started *without* the flake wrapper: the wrapper
        # exports PADMAP_BUILD_ID itself and would overwrite the fake one.
        env = dict(os.environ)
        env.update({
            "XDG_RUNTIME_DIR": str(runtime),
            "PADMAP_BUILD_ID": STALE_ID,
            "PYTHONPATH": str(REPO / "src"),
        })
        print("\nstarting a deliberately stale daemon...")
        stale = subprocess.Popen(
            [sys.executable, "-m", "padmap.cli", "serve"],
            env=env, start_new_session=True,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        before = wait_for(sock_path, 15)
        if before is None:
            print("FAIL: the stale daemon never came up")
            return 1
        print(f"  daemon pid {stale.pid}, build {before.get('build')!r}")
        if before.get("build") != STALE_ID:
            print(f"FAIL: expected build {STALE_ID!r}")
            return 1

        pegasus_env = dict(os.environ)
        pegasus_env.update({
            "XDG_RUNTIME_DIR": str(runtime),
            "XDG_CONFIG_HOME": str(config),
            "XDG_DATA_HOME": str(root / "data"),
            "DISPLAY": f":{DISPLAY_NUM}",
        })
        if args.skip_check:
            pegasus_env["PADMAP_SKIP_DAEMON_CHECK"] = "1"
            print("  --skip-check: wrapper check disabled, expecting FAIL")
        else:
            pegasus_env.pop("PADMAP_SKIP_DAEMON_CHECK", None)

        log_path = root / "pegasus.log"
        print(f"running the real {args.entry} entry point...")
        with xvfb(), log_path.open("w") as handle:
            # start_new_session so the whole tree can be taken down: Pegasus
            # does not exit on Qt.quit() from a theme, and leaving it running
            # would hold the test open.
            proc = subprocess.Popen(
                [entry], env=pegasus_env, start_new_session=True,
                stdout=handle, stderr=subprocess.STDOUT)
            try:
                # The check runs *before* Pegasus is exec'd, so
                # the interesting moment is over long before the UI settles.
                # Poll for the replacement rather than waiting for an exit
                # that never comes.
                deadline = time.monotonic() + 60
                while time.monotonic() < deadline:
                    if proc.poll() is not None:
                        break
                    state = daemon_state(sock_path, timeout=0.5)
                    if state is not None and state.get("build") != STALE_ID:
                        break
                    time.sleep(0.5)
            finally:
                _terminate_tree(proc)

        log = log_path.read_text(errors="replace")
        for line in log.splitlines():
            if "daemon" in line.lower() or "E2E:" in line:
                print("  " + line.strip())

        after = wait_for(sock_path, 15)
        if after is None:
            print("\nFAIL: no daemon is listening after Pegasus started.")
            print("  The wrapper stopped the stale one and did not replace it.")
            return 1

        print(f"\n  before: {before.get('build')!r}")
        print(f"  after:  {after.get('build')!r}")

        if after.get("build") == STALE_ID:
            print(f"\nFAIL: the stale daemon is still serving. The "
                  f"{args.entry} entry point's ensure-daemon step did not "
                  f"run or did not detect it.")
            print(f"  log: {log_path if args.keep else '(discarded)'}")
            return 1
        if not str(after.get("build", "")).startswith("/nix/store/"):
            print(f"\nFAIL: replacement reports an unexpected build "
                  f"{after.get('build')!r}")
            return 1

        # The theme is QML read from ~/.config at startup, so a link made once
        # by hand goes stale on every rebuild -- a fix live in the repo, present
        # in the build, and simply not running. The entry point repoints it.
        link = config / "pegasus-frontend" / "themes" / "padmap"
        if not link.is_symlink():
            print(f"\nFAIL: {link} was not created as a symlink")
            return 1
        target = os.readlink(link)
        if "padmap-pegasus-theme" not in target:
            print(f"\nFAIL: theme link points somewhere unexpected: {target}")
            return 1
        print(f"  theme link -> {target}")

        if bystander is not None and not alive(bystander):
            print(f"\nFAIL: the daemon on the real runtime dir (pid "
                  f"{bystander}) was killed. Restarting must be scoped to "
                  f"the socket it was asked about.")
            return 1

        print(f"\nPASS: the stale daemon was replaced by one running the "
              f"store build, via the real {args.entry} entry point.")
        if bystander is not None:
            print(f"      The unrelated daemon (pid {bystander}) survived.")
        return 0
    finally:
        # Whatever happened, do not leave a test daemon behind. Scoped to this
        # run's runtime dir by daemon_pids, so the user's real daemon is
        # untouchable from here.
        from padmap import protocol

        for pid in protocol.daemon_pids(str(root / "run")):
            try:
                os.kill(pid, 15)
            except OSError:
                pass
        if stale is not None and stale.poll() is None:
            stale.terminate()
        if not args.keep:
            shutil.rmtree(root, ignore_errors=True)
        else:
            print(f"\nkept: {root}")


if __name__ == "__main__":
    sys.exit(main())
